backend:
  name: github
  repo: sdminev/tengri-tech-next-js
  branch: main
  auth_endpoint: /api/auth/github
  base_url: https://tengri-tech-next-js.vercel.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "thumbnail", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
